### ISSUE TITLE
Incorrect version in manifest.json

### ISSUE THREAD

**Issue by bomberstudios** [levtolstoi/Nucleus#1]
Hi there!

It looks like you have an incorrect version in your `manifest.json` file (1.0, instead of 1.0.3) and that's making the Sketch Plugin Updater to fail (it's trying to update v1.0 with something that says "Hi, I'm v1.0 too!")

Could you take a look and fix it? Thanks!

**Comment by drunkbream** [comment]
@bomberstudios Thanks for your advertency. Is fixed.
